---
# tasks file for kiosk_mode
- name: Gather facts
  ansible.builtin.setup:

- name: Select kiosk packages for RHEL 9 and newer
  ansible.builtin.set_fact:
    kiosk_packages:
      - gnome-kiosk
      - gnome-kiosk-script-session
    kiosk_session: gnome-kiosk-script
    kiosk_script_name: gnome-kiosk-script
  when: ansible_facts['distribution_major_version'] | int >= 9

- name: Ensure hostname set
  ansible.builtin.hostname:
    name: "{{ inventory_hostname.split('.')[0] }}"

- name: Register with RHSM using provided credentials
  community.general.redhat_subscription:
    state: present
    username: "{{ rhsm_username }}"
    password: "{{ rhsm_password }}"
    auto_attach: "{{ rhsm_auto_attach }}"

- name: Install Gnome Desktop Environment
  ansible.builtin.dnf:
    name:
      - "@Server With GUI"
    skip_broken: true
    nobest: true
    state: present

- name: Create gdm configuration for kiosk kiosk_mode
  ansible.builtin.template:
    src: custom.conf
    dest: /etc/gdm/custom.conf
    mode: "0644"
  notify: Reboot

- name: Add the user 'kiosk'
  ansible.builtin.user:
    name: kiosk
    comment: kiosk user
    state: present
    shell: /bin/bash
    uid: 2000
    group: users
    create_home: true
    skeleton: true
  notify: Reboot

- name: Configure session for kiosk username /var/lib/AccountsService/users/kiosk
  ansible.builtin.template:
    src: kiosk.conf.j2
    dest: /var/lib/AccountsService/users/kiosk
    mode: "0600"

- name: Change default target to graphical.target
  ansible.builtin.file:
    src: /usr/lib/systemd/system/graphical.target
    dest: /etc/systemd/system/default.target
    state: link
  notify: Reboot

- name: Permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: https
    permanent: true
    state: enabled

- name: Install kiosk session packages
  ansible.builtin.dnf:
    name: "{{ kiosk_packages }}"
    state: present
  notify: Reboot

- name: Create directory local bin for kiosk mode
  ansible.builtin.file:
    path: /home/kiosk/.local/bin
    state: directory
    mode: "0755"
    owner: kiosk
    group: users
  notify: Reboot

- name: Create directory local bin for kiosk mode
  ansible.builtin.file:
    path: /home/kiosk/Desktop
    state: directory
    mode: "0755"
    owner: kiosk
    group: users
  notify: Reboot

- name: Create config directory to disable welcome screen
  ansible.builtin.file:
    path: /home/kiosk/.config/
    state: directory
    mode: "0755"
    owner: kiosk
    group: users
  notify: Reboot

- name: Create file to disable setup screens
  ansible.builtin.file:
    path: /home/kiosk/.config/gnome-initial-setup-done
    state: touch
    mode: "0755"
    owner: kiosk
    group: users

- name: Create shell script to start firefox
  ansible.builtin.template:
    dest: "/home/kiosk/.local/bin/{{ kiosk_script_name }}"
    src: files/redhat-kiosk.j2
    mode: "0755"
    owner: kiosk
    group: users
  notify: Reboot

- name: Flush handlers (will reboot if needed)
  ansible.builtin.meta: flush_handlers
