---
- name: Basic connectivity test
  hosts: localhost
  gather_facts: false
  become: false
  tasks:
    - name: Output collections
      ansible.builtin.command: ansible-galaxy collection list
      register: output

    - name: Show output
      ansible.builtin.debug:
        var: output.stdout_lines
